/*
xx***********************************************************************************xx
xx                                                                                   xx
xx  AUTOR/DESENVOLVEDOR...: Adriano Zanini (2020)                                    xx
xx  DATA DO CODIGO-FONTE..: DESDE 01/02/2010                                         xx
xx  E-MAIL................: indpcp2018@gmail.com                                     xx
xx                                                                                   xx
xx***********************************************************************************xx
xx                                                                                   xx
xx  SISTEMA...............: DBVenda Retaguarda / Frente de Caixa                     xx
xx  LINGUAGEM/DB..........: Delphi 10.3 Rio (32 bits) | Firebird 2.5 (32 bits)       xx
xx                                                                                   xx
xx***********************************************************************************xx
xx                                                                                   xx
xx Alguns sem qualquer ética profissional ou moral, tem comercializado esses fontes  xx
xx sem minha autorização. Pelas leis brasileiras de direitos autorais, ISSO É CRIME. xx
xx                                                                                   xx
xx***********************************************************************************xx
xx                                                                                   xx
xx Eu Adriano Zanini, sou autor/desenvolvedor. Se alguem te vendeu esses fontes      xx
xx sem minha autorização, você comprou um codigo-fonte pirata (não autorizo vender). xx
xx                                                                                   xx
xx***********************************************************************************xx
xx                                                                                   xx
xx Sou autor dos sitemas "VestisPCP", "IndPCP" e "DBVenda". Os fontes do "VestisPCP" xx
xx estão lá no GitHub.                                                               xx
xx Link no GitHub: https://github.com/ZaniniAdriano/VestisPCP                        xx
xx                                                                                   xx
xx***********************************************************************************xx
xx  COMERCIALIZE SOMENTE O SISTEMA COMPILADO (COM O NOME/INTERFACE QUE DESEJAR).     xx
xx  MUDE O QUE DESEJAR, CUSTOMIZE COMO QUISER. INCLUSIVE O NOME DO SISTEMA/PROJETO.  xx
xx                                                                                   xx
xx***********************************************************************************xx
*/

 -----------------------------------------------------------------------
 -- Use esse script quando desejar limpar a base de dados, para 
 -- instalar em seus clientes.
 -- Tabelas fiscais não serão excluidas (NCM/CEST/CST/ etc)
 -- Excluirá somente o necessário (confira abaixo). 
 -----------------------------------------------------------------------

set names none;

set sql dialect 3;

set clientlib 'fbclient.dll';

connect 'C:\projetos\fontes\Dados\Vazio\dbvenda.fdb'
user 'SYSDBA' password 'masterkey';

 
 -----------------------------------------------------------------------
 -- Primeiro: Excluir em efeito cascata
 -----------------------------------------------------------------------

 DELETE FROM VENDAS;
 DELETE FROM PEDIDOS;
 DELETE FROM FIN_CTARECEBER;
 DELETE FROM FIN_CTAPAGAR;
 DELETE FROM FIN_COMISSOES;
 DELETE FROM CTRL_CAIXA;
 DELETE FROM CTRL_BANCARIO;
 DELETE FROM COMPRA_PEDIDOS;
 DELETE FROM COMPRAS;
 DELETE FROM CAD_PRODUTOS;

 -----------------------------------------------------------------------
 -- Primeiro: Excluir outros cadastros
 -----------------------------------------------------------------------

 DELETE FROM CAD_CARTEIRA;
 DELETE FROM CAD_CONTAS;
 DELETE FROM CAD_DEPARTAMENTOS;
 DELETE FROM CAD_FORMAPAGTO;
 DELETE FROM CAD_SUBGRUPO;
 DELETE FROM CAD_GRUPO;
 DELETE FROM CAD_MOTIVOBAIXA;
 DELETE FROM CAD_DEPARTAMENTOS;
 DELETE FROM CAD_CLIENTES;
 DELETE FROM FIN_RECIBO;
 DELETE FROM FIN_TRANSFERENCIAS;
 DELETE FROM CAD_ATIVIDADES;
 DELETE FROM CAD_REGIOES;
 DELETE FROM FIN_CONTA_CORRENTE;

 DELETE FROM MOVIMENTO;
 DELETE FROM TPRECO;
 DELETE FROM USUARIO;

 DELETE FROM CONFIG_PARAMETROS;

 -----------------------------------------------------------------------
 -- Limpar tabela licença
 -----------------------------------------------------------------------
 DELETE FROM LICENCA;

 COMMIT WORK;

 -----------------------------------------------------------------------
 -- zerar IDs
 -----------------------------------------------------------------------
 execute procedure ZERAR_IDS;

 COMMIT WORK;

 
 
/******************************************************************************/
/***         INSERIR DADOS BÁSICOS INICIAIS                                 ***/
/******************************************************************************/


INSERT INTO CONFIG_PARAMETROS (EMPRESA, NOME, NOMEFANTASIA, CNPJ, IE, IM, CNAE, ENDERECO, NUMERO, BAIRRO, COMPLEMENTO, CEP, FONE, FAX, EMAIL, SITE, CONTATO, CIDADE, UF, NOMEPAIS, IDCIDADE, IDUF, IDPAIS, REGIME_TRIB, REGIME_TRIBALIQUOT, CODIFICACAO, SEPARADOR, GRUPO, SUBGRUPO, PRODUTO, ESTOQUENEGATIVO, SIT_TRIB, CLASSIF_FISCAL, NCM_PADRAO, QUALIDADE_PADRAO, FIN_JUROS, FIN_CARTORIO, FIN_COBDIAS, FIN_VENDAVISTABAIXAR, FIN_DIASBLOQUEAR, FIN_CTAPAG_LANCCX, FIN_CTAPAG_LANCBCO, FIN_CTAPAG_COMISSAO, FIN_CTAPAG_CONTACX, FIN_CTAPAG_PLANOCTA, FIN_CTAPAG_COMVECTO, FIN_CTAPAG_COMCTACX, FIN_CTAPAG_COMCTOCUSTO, FIN_CTAPAG_COMPLANCTA, FIN_CTAREC_LANCARCAIXA, FIN_CTAREC_LANCARBANCO, FIN_CTAREC_CONTACAIXA, FIN_CTAREC_PLANOCONTAS, FIN_BANCAO_LANCCX, COMPRA_PLNCTA, COMPRA_CFOP, COMPRA_IDFORNECEDOR, ALERTA_ESTQ, ALERTA_CTAREC, ALERTA_CTAREC_DIAS, ALERTA_CTAPAG, ALERTA_CTAPAG_DIAS, ALERTA_PEDIDOS, ALERTA_COBRANCA, ALERTA_VALID, ALERTA_VALID_DIAS, ALERTA_PEDCOMPRA, CFOP_VNDUFLOCAL, CFOP_VNDAUFEXTERNO, CFOP_DEVUFINTERNO, CFOP_DEVUFEXTERNO, CFOP_COMPUFINTERNO, CFOP_COMPUFEXTERNO, NFE_AMBIENTE, NFE_TIPODANFE, NFE_FORMAEMISSAO, NFE_MODELO, NFE_SERIE, NFE_SEQUENCIA, NFE_LOTE, INF_DATABASE, INF_IMGPRINCIPAL, INF_IMGIMPRIMIR, NFE_VERSAONFE, NFE_ENVIAREMAIL, CLI_DIASINATIVAR, CLI_DIASATRASO, VND_IDVENDPADRAO, VND_IDCLIENTEPADRAO, VND_IMPFATURA, PED_DIASENTREGA, PED_BAIXAESTOQUE, PED_MSG, FRETEPADRAO, TERC_DIAVCTO, PRODUCAO_FINALIZAR, TIPO_OPERACIONAL, TIPO_EMPRESA, RAMO_ATIVIDADE, SEGUIMENTO, ORIGEM_PRODUTOS, PRATICA_PRECOS, PADRAO_VENDA, SITECOTACAOMOEDA, QUANTIFICAR, ALIQPIS, ALIQCOFINS, REGTRIBISSQN, INDRATISSQN, IDFPAGTOPADRAO, CARNE_MSG, NFE_CERTIFICADO_LOCAL, NFE_CERTIFICADO_SENHA, NFE_CERTIFICADO_NUMSERIE, EMAIL_POP3HOST, EMAIL_POP3PORTA, EMAIL_SMTPHOST, EMAIL_SMTPPORTA, EMAIL_USUARIO, EMAIL_SENHA, EMAIL_SSLTSL, EMAIL_NOME, MODELOESCPOS, PORTAESCPOS, PDVTIPOFISCAL, NFCE_DANFE, NFCE_CFOP, NFCE_SEQUENCIA, NFCE_LOTE, NFCE_IDCSC, NFCE_CSC, NFCE_QRCODE, SSL_TIPO, TSL_TIPO, DANFEREPORT, RESPTEC_IDCSRT, RESPTEC_CSRT, RESPTEC_CNPJ, RESPTEC_XCONTATO, RESPTEC_EMAIL, RESPTEC_FONE, MFE_CHAVEACESSO, SATNFCE, SATMODELO, SATASSINATURA, SATCODATIV, SATDLL, SATLOGOLATERAL, SATQRCODELATERAL, SAT_SEQUENCIA, SAT_CFOP, ABRIRGAVETA, CONTAB_NOME, CONTAB_CPF, CONTAB_CRC, CONTAB_CNPJ, CONTAB_CEP, CONTAB_ENDERECO, CONTAB_NUMERO, CONTAB_BAIRRO, CONTAB_FONE, CONTAB_EMAIL, NFE_TIPOTRANSMISSAO) VALUES (1, '<RAZAO SOCIAL>', '<NOME FANTASIA>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BRASIL', NULL, NULL, 1058, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, '14122440', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 400, 'NAO', NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NAO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'WINCRYPT', 'LT_ALL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT WORK;

INSERT INTO USUARIO (ID, USERNAME, SENHA, BLOQUEAR, ONLINE, NIVEL, ACESSOVISIVEL) VALUES (1, 'ADMIN', '1', NULL, NULL, 'N', 'NAO');

COMMIT WORK;

INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'graficos.diversos', 'ACTGRAFICOCTARECEBER', 'Contas a Receber (Vencimentos)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'graficos.diversos', 'ACTGRAFICOCTARECEBERTOTAIS', 'Contas a Receber (Status)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'graficos.diversos', 'ACTGRAFICOCTAPAGAR', 'Contas a Pagar (Vencimentos)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'graficos.diversos', 'ACTGRAFICOCTAPAGARTOTAIS', 'Contas a Pagar (Status)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Clientes', 'ACCLIPESSOAJURIDICA', 'Pessoa Juridica', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Clientes', 'ACCLIPESSOAFISICA', 'Pessoa Fisica', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Clientes', 'ACCLIRELATORIO', 'Relatorio', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Fornecedores', 'ACFORCADASTRO', 'Cadastro', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Fornecedores', 'ACFORRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Vendedores', 'ACVENPESSOAJURIDICAFISICA', 'Cadastro', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Bancos', 'ACCADBCOCADASTRO', 'Bancos', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Bancos', 'ACCADBCOCONTACORRENTE', 'Conta Corrente e Boleto', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Bancos', 'ACCADCONTACAIXA', 'Conta Caixa', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Diversos', 'ACCADFORMAPAGTO', 'Forma de Pagamento', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Diversos', 'ACCADRAMOATIVIDADE', 'Ramo de Atividade', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Diversos', 'ACCADCFOP', 'CFOP', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Diversos', 'ACCADPLANOCONTAS', 'Plano de Contas', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Diversos', 'ACCADCENTROCUSTO', 'Centro de Custo', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Configurar.Sistema', 'ACCFGOPCOES', 'Configurações', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Configurar.Sistema', 'ACCFGUSUARIO', 'Usuário', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Configurar.Sistema', 'ACCFGSERVIDOR', 'Servidor SQL', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Configurar.Sistema', 'ACCFGBOLETO', 'Boleto Bancário', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Configurar.Sistema', 'ACCFGWINDOWS', 'Configurações Regionais do Windows', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Vendas', 'ACCADTABELAPRECO', 'Tabela de Preços', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Cadastro.Transportadora', 'ACTRPCADASTRO', 'Cadastro', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Cadastro', 'ACPRODMARCA', 'Marca', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Cadastro', 'ACPRODGRUPO', 'Grupo', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Cadastro', 'ACPRODSUBGRUPO', 'Subgrupo', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Cadastro', 'ACPRODNCMCEST', 'NCM/CEST', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Movimento', 'ACPRODPRODCADASTRO', 'Cadastro', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Movimento', 'ACPRODATUALIZARESTOQUE', 'Atualizar Estoque', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Movimento', 'ACPRODPESQUISAESTOQUEPRECO', 'Pesquisar Estoque/Preço', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Produto.Relatorio', 'ACPRODRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Help.Movimento', 'ACHELPLOGOFF', 'Log Off', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Help.Movimento', 'ACHELPMUDAREMPRESA', 'Mudar Empresa', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Help.Sistema', 'ACAPPAUTOR', 'Sobre o Sistema', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Help.Sistema', 'ACHELPSISTEMA', 'Sobre o Sistema', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Compras.Movimento', 'ACCOMPRAPEDIDOCOMPRA', 'Pedido', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Compras.Movimento', 'ACCOMPRAENTRADAXML', 'Entrada (XML)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Compras.Movimento', 'ACCOMPRAENTRADAMANUAL', 'Entrada (Manual)', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Compras.Relatorio', 'ACCOMPRARELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Pedido.Pedido', 'ACVPEDPEDIDO', 'Pedido', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Pedido.Relatorio', 'ACVENDAPEDRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Expressa', 'ACVENDAEXPRESSA', 'Venda Expressa', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Faturamento.Movimento', 'ACFATNOTAFISCAL', 'NF-e', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Faturamento.Movimento', 'ACFATNOTAEMITIDA', 'Consultar', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Venda.Faturamento.Relatorio', 'ACFATRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Receber', 'ACFINRECLANCAMENTO', 'Lançamentos', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Receber', 'ACFINRECBAIXA', 'Baixar', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Receber', 'ACFINRECBOLETO', 'Boleto Bancário', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Receber', 'ACFINRECCARNE', 'Carnê Pagamento', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Receber', 'ACFINRECRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Pagar', 'ACFINPAGLANCAMENTO', 'Lançamentos', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Pagar', 'ACFINPAGBAIXAR', 'Baixar', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Pagar', 'ACFINPAGRELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Cheque', 'ACCHQPAGAR', 'Pagamento', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Cheque', 'ACCHQRECEBER', 'Recebimento', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Banco', 'ACFINBCOCONTROLE', 'Controle Bancário', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Banco', 'ACFINBCOTRANFERENCIA', 'Tranferência', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Caixa', 'ACFINCXCONTROLE', 'Lançamento Caixa', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Caixa', 'ACFINCXFLUXOCAIXA', 'Relatório Caixa', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Diversos', 'ACFINDIVRECIBO', 'Recibo', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Expedicao.Movimento', 'ACEXPEDICAOETIQUETA', 'Etiqueta de Embalagem', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Expedicao.Movimento', 'ACEXPEDICAOROMANEIO', 'Romaneio de Transporte', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Expedicao.Movimento', 'ACEXPEDICAORELATORIO', 'Relatório', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Comissao', 'ACFINCOMISSAO', 'Comissão Vendas', 'SIM');
INSERT INTO USUARIOACESSO (ID, CATEGORIA, MENU, TITULO, ACESSO) VALUES (1, 'Financeiro.Comissao', 'ACFINCOMISSAORELATORIO', 'Relatório', 'SIM');

COMMIT WORK;

/******************************************************************************/
/***                               DADOS PADRONIZADOS                       ***/
/*** CLIENTE (PDV) E FORMA DE PAGAMENTO (PDV)                               ***/
/******************************************************************************/


INSERT INTO CAD_CLIENTES (CODIGO, CPF_CNPJ, TIPO, CLASSIFICACAO, NOME, RG_IE, NOME_FANTASIA, STATUS, ATIVO, ATIVODATA, DATA, DATA_NASCIMENTO, ULTIMAVENDA_DATA, ULTIMAVENDA_ORIGEM, CONTATO, ORG_EMISSOR, SEXO, FILIACAO_NOMEPAI, FILIACAO_NOMEMAE, ESTADO_CIVIL, CONJUGE_CPF, CONJUGE_NOME, CXP, CEP, ENDERECO, NUMERO, COMPLEMENTO, BAIRRO, IDCIDADE, NOMECIDADE, CODIGOUF, UF, DDD_FONE, FONE, DDD_FAX, FAX, DDD_CELULAR, CELULAR, DDD_VOIP, VOIP, EMAIL, SITE, REFERENCIA, VENDEDOR, REGIAO, TRANSPORTADORA, ESTRANGEIRO, NATURALIDADE, CREDITO_LIMITE, CREDITO_UTILIZADO, CREDITO_DISPONIVEL, BLOQUEADO, PLANO_CONTAS, CFOP, CENTROCUSTO, CONTACORRENTE, ENDCOB_ENDERECO, ENDCOB_BAIRRO, ENDCOB_DDD, ENDCOB_FONE, ENDCOB_CEP, ENDCOB_CXP, ENDCOB_IDCIDADE, ENDCOB_NOMECIDADE, ENDCOB_UF, PROTESTO, PROTESTO_DATA, ETIQUETA, NACIONALIDADE, CONVENIO, ATIVIDADE, OBSERVACAO, OBS_SERASA, OBS_SINTEGRA, CONJUGE_DNASCIMENTO, CONJUGE_EMPRESA, CONJUGE_FONE, CONJUGE_ENDERECO, CONJUGE_CIDADE, CONJUGE_UF, CONJUGE_CARGO, CONJUGE_TEMPO, CONJUGE_SALARIO, EMPREGO_EMPRESA, EMPREGO_FONE, EMPREGO_ENDERECO, EMPREGO_CIDADE, EMPREGO_UF, EMPREGO_CARGO, EMPREGO_TEMPO, EMPREGO_SALARIO, COMISSAO, COMISSIONAR, SALARIO, TRANSPORTADORA_PLACA, TRANSPORTADORA_CIDADE, TRANSPORTADORA_UF, VALOR_SERVICOS, SEGUIMENTO, ALERTA, IDGRUPO, SKYPE, WHATSAPP, IDFORMAPAGTO, IDTIPOPESSOA, IDCOMISSAOPADRAO, IDCOMISSAOCOMPOSTA, IDTABELAPRECO, TIPOCALCULCOMISSAO, COMISSAOPAGTOOBRIGATORIO, COMISSAOFECHAMENTODIA, COMISSAOCALCULAR, ANIVERSARIO_DIAMES, ANIVERSARIO_MESANO, ORIGEMCADASTRO, FORMA_COMERCIALIZACAO, TIPO_COMERCIALIZACAO, MEI, LIBERARPAGAMENTO, MENSAGEMATIVA, MENSAGEM1, MENSAGEM2, PREPOSTO_IDVENDEDOR, VENDEDORTIPOCOMISSAO, IDPORTE, CONTRIBUINTEICMS) VALUES (1, NULL, 'CLIENTE', 'F', 'CONSUMIDOR FINAL (PDV)', NULL, NULL, NULL, 'S', '2020-08-06', '2020-08-06', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'S', 'S', NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT WORK;

INSERT INTO CAD_FORMAPAGTO (CODIGO, NOME, ACRESCIMO, DESCONTO, VENCIMENTO_DIA, TIPO_PAGAMENTO, ARRED_SN, PARCELAMINIMA, ARREDONDAR, STATUS) VALUES (1, 'PAGAMENTO A VISTA (PDV)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT WORK;


SET GENERATOR GEN_CAD_CLIENTES_ID TO 1;


SET GENERATOR GEN_CAD_FORMAPAGTO_ID TO 1;

COMMIT WORK;

